apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
  labels:
    app: static-site
spec:
  replicas: 2                       # two copies -> load balancing + resilience
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site            # MUST match the selector above
    spec:
      containers:
        - name: web
          image: ajaypokharel444/static-site-hannah:1.0   # pulled from Docker Hub
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:            # "ready to receive traffic?"
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:             # "still alive? restart if not"
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests: { cpu: "25m", memory: "32Mi" }
            limits:   { cpu: "100m", memory: "64Mi" }
